spring:
  application:
    name=lucky-vicky-auction:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'prometheus'

server:
  tomcat:
    mbeanregistry:
      enabled: true