spring:
  application:
    name: lucky-vicky-auction

  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: off
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'prometheus'

server:
  tomcat:
    mbeanregistry:
      enabled: true

lock:
  provider: redisson
  lettuce:
    max_retry: 10
    retry_duration: 50
    lease_time: 200
  redisson:
    wait_time: 500
    lease_time: 200

stream:
  key: LVA-Stream
  consumer:
    groupName: LVA-Group
